package main

import (
	"bufio"
	"context"
	"crypto/md5"
	"encoding/base64"
	"encoding/hex"
	"fmt"
	"log"
	"os"
	"runtime"
	"strings"
	"sync"
	"sync/atomic"
	"time"
)

// bruteForce performs a dictionary-based HMAC secret brute-force attack.
// FIX: Uses atomic.Int64 for thread-safe attempt counting.
// FIX: Uses context.WithCancel to stop all workers when a key is found.
// FIX: No more data race on bare *int.
func bruteForce(cfg *Config) {
	alg, err := getAlg(cfg.Token)
	if err != nil {
		log.Fatalf("Failed to extract algorithm: %v", err)
	}
	if !strings.HasPrefix(alg, "HS") {
		log.Printf("Warning: Algorithm %s is not HMAC; brute-force may not apply", alg)
	}

	ctx, cancel := context.WithCancel(context.Background())
	defer cancel()

	secretsCh := make(chan string, cfg.Workers*10)
	resultsCh := make(chan string, 1)
	var wg sync.WaitGroup
	var attempts atomic.Int64

	workers := cfg.Workers
	if workers <= 0 {
		workers = runtime.NumCPU()
	}

	for i := 0; i < workers; i++ {
		wg.Add(1)
		go func() {
			defer wg.Done()
			for {
				select {
				case <-ctx.Done():
					return
				case secret, ok := <-secretsCh:
					if !ok {
						return
					}
					attempts.Add(1)
					if verifySignature(cfg.Token, secret, alg) {
						select {
						case resultsCh <- secret:
						default:
						}
						cancel()
						return
					}
				}
			}
		}()
	}

	// Load dictionary in a separate goroutine
	go func() {
		if err := loadDictionaryWithTransforms(cfg.DictFile, secretsCh); err != nil {
			log.Printf("Dictionary load error: %v", err)
		}
	}()

	// Wait for all workers to finish, then close results channel
	go func() {
		wg.Wait()
		close(resultsCh)
	}()

	// Collect result
	var found string
	select {
	case found = <-resultsCh:
	case <-time.After(cfg.Timeout):
		if cfg.Timeout == 0 {
			found = <-resultsCh
		}
	}

	report := Report{
		FoundSecret: found,
		Attempts:    attempts.Load(),
	}
	if found != "" {
		addResult(&report, newResult(
			"Weak HMAC Secret (Brute-force)",
			"Token-level",
			"HIGH",
			"HMAC signing secret was cracked via dictionary brute-force with key transforms",
		))
		report.Recommendations = []string{
			"Use random 256-bit secrets generated by CSPRNG (e.g., openssl rand -base64 64)",
			"Prefer HS512 over HS256",
			"Store secrets in KMS (HashiCorp Vault, AWS KMS, Azure Key Vault)",
			"Never commit secrets to source control or Docker images",
			"Implement key rotation with kid header support",
		}
		fmt.Printf("[VULNERABLE] Secret found: %s (after %d attempts)\n", found, attempts.Load())
	} else {
		report.Recommendations = []string{
			"Secret not found in dictionary; ensure secrets are 256-bit random",
			"Use CSPRNG-generated secrets (openssl rand -base64 64)",
		}
		fmt.Printf("[SAFE] No secret found (tried %d candidates)\n", attempts.Load())
	}
	writeReport(cfg.ReportFile, report)
}

// loadDictionaryWithTransforms reads a dictionary file and feeds each word plus
// 5 transformations (plain, MD5-32, MD5-16, Base64-Std, Base64-URL) to the channel.
func loadDictionaryWithTransforms(file string, ch chan<- string) error {
	f, err := os.Open(file)
	if err != nil {
		return fmt.Errorf("failed to open dictionary: %w", err)
	}
	defer f.Close()
	defer close(ch)

	scanner := bufio.NewScanner(f)
	scanner.Buffer(make([]byte, 0, 1024*1024), 1024*1024)
	for scanner.Scan() {
		word := strings.TrimSpace(scanner.Text())
		if word == "" {
			continue
		}
		ch <- word
		ch <- md5Hex32(word)
		ch <- md5Hex16(word)
		ch <- base64Std(word)
		ch <- base64URL(word)
	}
	return scanner.Err()
}

func md5Hex32(s string) string {
	hash := md5.Sum([]byte(s))
	return hex.EncodeToString(hash[:])
}

func md5Hex16(s string) string {
	hash := md5.Sum([]byte(s))
	return hex.EncodeToString(hash[:])[:16]
}

func base64Std(s string) string {
	return base64.StdEncoding.EncodeToString([]byte(s))
}

func base64URL(s string) string {
	return base64.URLEncoding.EncodeToString([]byte(s))
}
